### ISSUE TITLE
Add documentation for key/signature based authentication to gRPC

### ISSUE THREAD

**Issue by llucax** [frequenz-floss/frequenz-api-dispatch#14]
### What's needed?

The UI allows users to create API keys and secrets to be able to authenticate their applications against the cloud APIs. This API needs to support this kind of authentication.

Please have a look at the details in:

* https://github.com/frequenz-io/rnd/issues/141

**Comment by stefan-brus-frequenz** [comment]
https://github.com/frequenz-io/api-dispatch/pull/49

**Comment by thomas-nicolai-frequenz** [comment]
We also need to add documentation to the protobuf spec that outlines that this API requires authentication and how this is to be implemented, right? Here is a suggestion:

```Protobuf
syntax = "proto3";

package example;

// The MyService provides an API for managing various resources.
// ALL requests to this service must be signed. The key and signature 
// should be added to the request metadata (HTTP headers). The signature 
// should be computed using the HMAC-SHA256 algorithm and the user's secret key.
service MyService {
    ...
}
```

**Comment by Marenz** [comment]
Support has been added, documentation is still missing though
