### ISSUE TITLE
"Yearly" frequency missing from recurrence rule

### ISSUE THREAD

**Issue by stefan-brus-frequenz** [frequenz-floss/frequenz-api-dispatch#157]
### What happened?

The "yearly" frequency is not available in the current Recurrence Rule definition, making the `bymonths` field redundant.

### What did you expect instead?

"Yearly" should be added to the frequency enum. See the RFC: https://datatracker.ietf.org/doc/html/rfc5545

### Affected part(s)

The protocol buffer definition files (part:protobuf)

**Comment by thomas-nicolai-frequenz** [comment]
The enum needs extending like this:

```Diff
  enum Frequency {
    FREQUENCY_UNSPECIFIED = 0;
    FREQUENCY_MINUTELY = 1;
    FREQUENCY_HOURLY = 2;
    FREQUENCY_DAILY = 3;
    FREQUENCY_WEEKLY = 4;
    FREQUENCY_MONTHLY = 5;
+  FREQUENCY_YEARLY = 6;
  }
```
