### ISSUE TITLE
Do not allow updating dispatch `type`

### ISSUE THREAD

**Issue by thomas-nicolai-frequenz** [frequenz-floss/frequenz-api-dispatch#158]
### What's needed?

Remove support for changing the dispatch type after creation.

### Proposed solution

```patch
// Message to update the dispatch with the given ID, with the given attributes
message DispatchUpdateRequest {
  // Message containing the updated dispatch attributes
  message DispatchUpdate {
       ...
    }

-    // The type of dispatch
-    optional string type = 1;

```

### Use cases

A user should not be able to change the dispatch type after creation as this would mean handing over an existing dispatch from one actor to another.

### Alternatives and workarounds

Delete dispatch and create a new one instead of trying to update the type of an existing dispatch.

**Comment by Marenz** [comment]
done in https://github.com/frequenz-floss/frequenz-api-dispatch/pull/172
