### ISSUE TITLE
Improve `payload` documentation

### ISSUE THREAD

**Issue by thomas-nicolai-frequenz** [frequenz-floss/frequenz-api-dispatch#163]
### What's needed?

Extend the documentation for the [payload](https://github.com/frequenz-floss/frequenz-api-dispatch/blob/7f806cecf0a31fed004182409d6e4ecefe45bcce/proto/frequenz/api/dispatch/v1/dispatch.proto#L123C1-L124C39) parameter as shown below:

 * Creates a new dispatch with the specified payload.
 * Note: The payload must conform to the following constraints:
 * - Maximum nesting depth of 5. Payloads with structures nested deeper than this will be rejected.
 * - Payloads must be valid according to the JSON structure.

### Proposed solution

```Patch
message Dispatch {
  // ...
  
  
  // The dispatch payload.
+  // 
+  // Note!!! 
+  //     The payload field allows for flexible JSON data to be associated with this dispatch.
+  //     The payload must adhere to the following constraints:
+  //      - Maximum JSON nesting depth: 5 levels. 
+  //      - The data should not contain executable code or scripts.
+  //      - Ensure all data is properly sanitized and encoded.
+  //      - The total size of the payload should not exceed 50 KB.
  google.protobuf.Struct payload = 11;
```

**Comment by llucax** [comment]
I can see adding size limits being useful to avoid resources over-usage, but any particular reason for adding a nesting limit?

Also it would be probably good to be more clear if these are just guidelines or if the server will reject requests not following these rules. In particular the "data is properly sanitized and encoded" seems not implementable in the server side, as the payload will be obscure to the server.

Also nitpick, maybe we shouldn't talk about JSON in this context, it is a `Struct` in protobuf lingo. Related to that, the 50K limit is in protobuf wire format or do you expect the server to actually convert it to JSON and take the size of the JSON text?

**Comment by thomas-nicolai-frequenz** [comment]
> I can see adding size limits being useful to avoid resources over-usage, but any particular reason for adding a nesting limit?

Well if the nesting is infinite it would take infinite time to expand it. I'd like to avoid a situation where this is used for some kind of attack.
