### ISSUE TITLE
Requirements for FCR balancing actor

### ISSUE THREAD

**Issue by stefan-brus-frequenz** [frequenz-floss/frequenz-api-dispatch#18]
### What's needed?

This is a tracking issue for the addition of a new settings type for FCR balancing dispatches. Requirements still need to be gathered.

**Comment by Marenz** [comment]
One requirement is the support for reoccuring events.

**Comment by thomas-nicolai-frequenz** [comment]
@stefan-brus-frequenz the requirements are pretty much of whats defined in the marshmallow config files. Do you need more input from my side?
