### ISSUE TITLE
Consider using `DispatchMetadata` instead of `DispatchDetail`

### ISSUE THREAD

**Issue by llucax** [frequenz-floss/frequenz-api-dispatch#193]
### What's needed?

Currently we have a `Dispatch` object and a `DispatchDetail` object, that stores metadata plus the `Dispatch`. It is not very clear what each object stores.

### Proposed solution

Change:

```protobuf
message Dispatch {
    // data
}

message DispatchDetail {
    // metadata
    Dispatch dispatch;
}

message CreateMicrogridDispatchResponse {
  DispatchDetail dispatch = 1;
}
```

To:

```protobuf
message Dispatch {
    // data
}

message DispatchMetadata {
    // metadata
    Dispatch dispatch;
}

message CreateMicrogridDispatchResponse {
  DispatchMetadata dispatch_metadata = 1;
  Dispatch dispatch = 2;
}
```

This will add a bit more duplication, as now messages having metadata will need to declare 2 fields instead of one, but for me it makes things much clearer and reduce ambiguity (for example, if in the code I see `response.dispatch` I don't know if I'm referencing a `Dispatch` or `DispatchDetail` so easily, while `response.dispatch_metadata` is pretty obvious).

**Comment by Marenz** [comment]
Yeah I'm also pretty unhappy with the naming, though there was some discussion surround this already somewhere

**Comment by tiyash-basu-frequenz** [comment]
I also think we have the `DispatchDetail` and `Dispatch` messages the other way around logically.
- A `Dispatch`, IMO, is a concrete entity, and therefore will always have an ID and a timestamp, but these are parts of `DispatchDetail` message instead.
- The `Dispatch` message ATM is not actually a dispatch, but just a set of parameters for a dispatch (like a constructor's parameters).

But probably that boat has sailed already :)

IMO, there should be one message that somehow represents the dispatch parameters, the dispatch ID, and its create and modify timestamps. I would not make it the response message, because that is very to close to the RPC, and possibly every user (client and service) eventually will make its own struct with these fields. If this were to be a separate message (something similar to `DispatchDetail` but maybe better named, then we can have a much better resolution of this issue.

**Comment by Marenz** [comment]
I already argued with Tom in that direction and was met with "This is aligned across APIs", e.g. [here](https://github.com/frequenz-floss/frequenz-api-electricity-trading/blob/v0.x.x/proto/frequenz/api/electricity_trading/v1/electricity_trading.proto#L297)

The implication was that if we want to change this it has implications for all the other APIs as well.

This was my suggestion at the time:
```
// Represents a dispatches data, including its type, start time, duration, component selector,
message DispatchData {
   string type = 1;
  google.protobuf.Timestamp start_time = 2;
  optional uint32 duration = 3;
  ComponentSelector selector = 4;
  [..]
}

// Represents a dispatch, including its metadata
message DispatchWithMetadata {
  // Unique identifier of the microgrid dispatch.
  uint64 dispatch_id = 1;

  // UTC Timestamp when the order was created.
  google.protobuf.Timestamp create_time = 3;

  // UTC Timestamp of the last update to the order.
  google.protobuf.Timestamp modification_time = 4;

  // The dispatch data
  DispatchData data = 2;
}
```

An alternative was  similar to lucas idea..

Though, luca:
```
message Dispatch {
    // data
}

message DispatchMetadata {
    // metadata
    Dispatch dispatch;
}

message CreateMicrogridDispatchResponse {
  DispatchMetadata dispatch_metadata = 1;
  Dispatch dispatch = 2;
}
```
that example is weird. `DispatchMetadata` seems to contain the data as well and then you're specifying it twice in the create response message (once in the `DispatchMetadata` object once directly `Dispatch`)

**Comment by Marenz** [comment]
@frequenz-floss/api-electricity-trading-team are you happy with the structure of your `OrderDetail` and `Order` messages and other `_detail`?

```
// Represents an order with full details, including its ID, state and associated
message OrderDetail {
  // Inner message providing details about the current state of the order.
  message StateDetail {
      // [..]
    }

   // [..]

    // Current state of the order.
    OrderState state = 1;
    // [..]
  }

  // Unique identifier of the order.
  uint64 order_id = 1;

  // The details of the order.
  Order order = 2;

  //[..]
}
```

I personally found it confusing to read the comment "The details of the order" in the message `OrderDetail` referring to  the `Order` message (which is not named "OrderDetail" though..

**Comment by Marenz** [comment]
On the other hand, when it was said "synced across APIs" I thought this implies that more than one other API dose this, but I actually found only the Etrading API uses the `*_detail` or `*Detail` pattern.

So we can still change this and keep it consistent.

**Comment by Marenz** [comment]
Generally, my suggestion would be: 
* `DispatchMetadata` -> as the name says, only data like creation/modification/microgrid_id
* `DispatchData` -> only the actual data, like type, start_type, recurrence etc
* `Dispatch` -> containing both messages above, a full dispatch object with all details.

That seems to me the most straightforward solution

**Comment by llucax** [comment]
> This was my suggestion at the time:
> 
> ```
> // Represents a dispatches data, including its type, start time, duration, component selector,
> //
> // Timezone Note: Timestamps are in UTC. It is the responsibility of each microgrid to translate UTC
> // to its local timezone.
> message DispatchData {
> ...
> }
> 
> // Represents a dispatch, including its metadata
> message DispatchWithMetadata {
>   // Unique identifier of the microgrid dispatch.
>   uint64 dispatch_id = 1;
> 
>   // UTC Timestamp when the order was created.
>   google.protobuf.Timestamp create_time = 3;
> 
>   // UTC Timestamp of the last update to the order.
>   google.protobuf.Timestamp modification_time = 4;
> 
>   // The dispatch data
>   DispatchData data = 2;
> }
> ```

I'm fine with `DispatchData` instead of `Dispatch` (I wasn't sure if to suggest that too), but I think the composition and the name in `DispatchWithMetadata` makes things more complicated and verbose and it only gives you a little bit less typing for messages having both.

Also having the metadata separately, opens the door to add function to retrieve **only** the metadata, like the `HEAD` http method, maybe you just want to check if a dispatch was updated, so you retrieve only the metadata, avoiding retrieving a lot of data in the case it didn't changed.

**Comment by llucax** [comment]
> Generally, my suggestion would be:
> 
>     * `DispatchMetadata` -> as the name says, only data like creation/modification/microgrid_id
> 
>     * `DispatchData` -> only the actual data, like type, start_type, recurrence etc
> 
>     * `Dispatch` -> containing both messages above, a full dispatch object with all details.
> 
> 
> That seems to me the most straightforward solution

I can live with this too if you want the composite message.

**Comment by llucax** [comment]
@thomas-nicolai-frequenz you have an upcoming riot... :laughing:

**Comment by ghost** [comment]
> @frequenz-floss/api-electricity-trading-team are you happy with the structure of your OrderDetail and Order messages and other _detail?

We had discussions about this naming with @thomas-nicolai-frequenz back in September. We weren't the most satisfied with it but didn't really find any more convincing alternatives so we concluded that `OrderDetail` was fitting enough. I don't have the strongest opinions about this but if you wanna make a change I do think that it should be aligned across APIs and thus make sense for all different cases (not just Dispatch).

**Comment by thomas-nicolai-frequenz** [comment]
I'm OK with @Marenz proposal. I'm just not sure it really improves so much though or makes it more clear. The term Metadata is generally very ambiguous. Its more a matter of personal taste imho.

> if you want the composite message.

Yes, indeed we do! It doesn't make sense to split this up into two messages as it would double up the number of requests and I can't see the advantage of that.

**Comment by Marenz** [comment]
> it would double up the number of requests and I can't see the advantage of that.

No no, a message is still sent as one request, no matter if it contains other sub-messages, that's untouched by this

**EDIT:** Nevermind, I misunderstood the comment.

**Comment by llucax** [comment]
> Yes, indeed we do! It doesn't make sense to split this up into two messages as it would double up the number of requests and I can't see the advantage of that.

No, the response is still only one, it is just you have to specify 2 fields in the response instead of one. But I'm fine with having the composite message explicit too.

> I'm OK with @Marenz proposal. I'm just not sure it really improves so much though or makes it more clear. The term Metadata is generally very ambiguous. Its more a matter of personal taste imho.

I think one fundamental difference with having the metadata as a separate message that doesn't include the data is the ability to have responses that only includes metadata in the future, like the `HEAD` HTTP method.
