### ISSUE TITLE
Charge selector property name to target

### ISSUE THREAD

**Issue by ktickner** [frequenz-floss/frequenz-api-dispatch#202]
As per [this conversation](https://frequenz-io.slack.com/archives/C02VC9G9BHQ/p1727356979010639), the word selector is a little vague and doesn't feel accurate in describing the purpose, especially in the context of a UI.
We would like to change the property name to target so that it feels more intuitive and also matches the UI label, so that we have parity between the two contexts.

**Comment by Marenz** [comment]
Any progress on this @ktickner ?
