### ISSUE TITLE
Add `update_time` field to Dispatch message

### ISSUE THREAD

**Issue by stefan-brus-frequenz** [frequenz-floss/frequenz-api-dispatch#21]
### What's needed?

Update time is required to keep track of when a dispatch was last updated, mainly for caching purposes. It should be updated whenever an update request message touches on a dispatch, and set to the same timestamp as `create_time` when the dispatch is created.

**Comment by thomas-nicolai-frequenz** [comment]
We can either use the latest update time or a counter (revision number) both is fine imho.
