### ISSUE TITLE
Header documentation and package versioning

### ISSUE THREAD

**Issue by thomas-nicolai-frequenz** [frequenz-floss/frequenz-api-dispatch#32]
### What's needed?

```Patch
-// Dispatch gRPC API definition.
-//
-// Copyright:
-// Copyright 2022 Frequenz Energy-as-a-Service GmbH
-//
-// License:
-// All rights reserved.
-
-// protolint:disable MAX_LINE_LENGTH
+// Copyright 2023 Frequenz Energy-as-a-Service GmbH
+//
+// Licensed under the MIT License (the "License");
+// you may not use this file except in compliance with the License.

...

- package frequenz.api.dispatch;
+ package frequenz.dispatch.v1;

+// Service providing operations related to dispatching microgrid components.
service DispatchService {
...
```
@tiyash-basu-frequenz @llucax FYI

### Proposed solution

Applying the provided patch as needed.

### Additional context

This is also being introduced for the Microgrid API:
https://github.com/frequenz-floss/frequenz-api-microgrid/issues/77

**Comment by thomas-nicolai-frequenz** [comment]
@stefan-brus-frequenz please also adjust the folder structure to reflect the package version.

**Comment by llucax** [comment]
Sorry for looking so late, but any reason why the extra verboseness about having to comply with the license @thomas-nicolai-frequenz ?

This is what we have so far in the repo-config templates:

```
// Copyright:
// Copyright {% now 'utc', '%Y' %} {{cookiecutter.author_name}}
//
// License:
// {{cookiecutter.license}}
```

If we really want to stick to this new style, we should update the repo-config templates...
