### ISSUE TITLE
Streaming rpc method

### ISSUE THREAD

**Issue by thomas-nicolai-frequenz** [frequenz-floss/frequenz-api-dispatch#84]
### What's needed?

We need an additional RPC method that supports streaming of dispatches for a microgrid.

### Proposed solution

Add a new RPC called StreamMicrogridDispatches:

```Diff
service MicrogridDispatchService {
  // Returns a list of all dispatches
  rpc ListMicrogridDispatches(DispatchListRequest) returns (DispatchList);

+  // Streaming RPC for receiving dispatch updates for a given microgrid
+  rpc StreamMicrogridDispatches(StreamMicrogridDispatchesRequest) returns (stream StreamMicrogridDispatchesResponse);

  // Create a new dispatch
  rpc CreateMicrogridDispatch(DispatchCreateRequest) returns (google.protobuf.Empty);

  // Update a dispatch
  rpc UpdateMicrogridDispatch(DispatchUpdateRequest) returns (google.protobuf.Empty);

  // Get a single dispatch
  rpc GetMicrogridDispatch(DispatchGetRequest) returns (Dispatch);

  // Delete a given dispatch
  rpc DeleteMicrogridDispatch(DispatchDeleteRequest) returns (google.protobuf.Empty);
}

+// Subscribe to a stream of microgrid dispatch requests.
+// This method provides real-time updates on newly or updated dispatch requests for edge-based 
+// realtime decision making.
+ message StreamMicrogridDispatchesRequest {
+   // ID of the microgrid to subscribe to
+   uint64 microgrid_id = 1;  
+ }

+ // Response to a subscription request for a stream of microgrid dispatches.
+ // Real-time information on dispatches affecting a certain microgrid are pushed through this response.
+ message StreamMicrogridDispatchesResponse {
+   // Dispatch record returned. 
+   Dispatch dispatch = 1;       
+ }


```

### Use cases

An actor would like to receive any scheduled dispatches as soon as they are created or updated.

### Alternatives and workarounds

Polling.

**Comment by Marenz** [comment]
It would also be useful to receive dispatches once they have been updated

**Comment by llucax** [comment]
FYI @thomas-nicolai-frequenz, you can always hide comments to avoid distraction, but still have them for the records.

![image](https://github.com/frequenz-floss/frequenz-api-dispatch/assets/1031485/4bf71df6-7da7-40d0-90f3-ad29767f3c8d)

You can even choose a reason:

![image](https://github.com/frequenz-floss/frequenz-api-dispatch/assets/1031485/49fbd37f-c289-4cb6-95a6-d39eaf53630a)

Feel free to hide this comment after you read it :laughing: 

![self-destruct](https://y.yarn.co/1ad32596-3c8c-4807-ba79-b2d28cc4f718_text.gif)
