### ISSUE TITLE
Restructure RPC methods

### ISSUE THREAD

**Issue by thomas-nicolai-frequenz** [frequenz-floss/frequenz-api-dispatch#88]
### What's needed?

As discussed we wan't to restructure the API in a way that it can more easily extendible in the future and doesn't break backwards compatibility. 

### Proposed solution

The proposed changes to the Protobuf definition are:

```Diff
service MicrogridDispatchService {
  // Returns a list of all dispatches
-  rpc ListMicrogridDispatches(DispatchListRequest) returns (DispatchList);
+ rpc ListMicrogridDispatches(ListMicrogridDispatchesRequest) returns (ListMicrogridDispatchesResponse);

  // Create a new dispatch
-  rpc CreateMicrogridDispatch(DispatchCreateRequest) returns (google.protobuf.Empty);
+  rpc CreateMicrogridDispatch(CreateMicrogridDispatchRequest) returns (CreateMicrogridDispatchResponse);

  // Update a dispatch
-  rpc UpdateMicrogridDispatch(DispatchUpdateRequest) returns (google.protobuf.Empty);
+  rpc UpdateMicrogridDispatch(UpdateMicrogridDispatchRequest) returns (UpdateMicrogridDispatchResponse);

  // Get a single dispatch
-  rpc GetMicrogridDispatch(DispatchGetRequest) returns (Dispatch);
+  rpc GetMicrogridDispatch(GetMicrogridDispatchRequest) returns (GetMicrogridDispatchResponse);

  // Delete a given dispatch
-  rpc DeleteMicrogridDispatch(DispatchDeleteRequest) returns (google.protobuf.Empty);
+  rpc DeleteMicrogridDispatch(DeleteMicrogridDispatchRequest) returns (DeleteMicrogridDispatchResponse);
}
```

### Use cases

Keeping backwards compatibility in case we need to extend the API.

### Alternatives and workarounds

New API version.

**Comment by llucax** [comment]
Out of curiosity, which kind of dispatches do you envision in the future that are not microgrid dispatches?

**Comment by thomas-nicolai-frequenz** [comment]
> envision in the future that are not microgrid dispatches

None as of now. We have two main higher level entities in the system:

1. Microgrids
2. Gridpools

Using the `Microgrid` prefix makes it more clear what the context is that dispatches are applied to e.g. microgrids and not gridpools or something else.  If the we remove the prefix it might not be as clear anymore. Hence right now people know  that dispatches are only used for microgrids as leaving this out might create ambiguity. We already deal with quite a lof complexity and having more ambiguity is not helpful in my opinion. I also don't see what harm it does. Many people don't even know that the term dispatch has a special meaning in the [energy industry](https://en.wikipedia.org/wiki/Dispatchable_generation).

Also we should move that discussion somewhere else as I don't think it belongs here.

**Comment by Marenz** [comment]
Solved in https://github.com/frequenz-floss/frequenz-api-dispatch/pull/172
