### ISSUE TITLE
Renames `dispatches` to `dispatch_list`

### ISSUE THREAD

**Issue by thomas-nicolai-frequenz** [frequenz-floss/frequenz-api-dispatch#89]
### What's needed?

In order to align with the other API specs its suggested to rename `dispatches` to `dispatch_list`.

**Comment by thomas-nicolai-frequenz** [comment]
An alternative would be to rename it to `list_of_dispatches`.

**Comment by llucax** [comment]
I remember there was an internal discussion about this and many people (me include :stuck_out_tongue_closed_eyes: ) preferred `dispatches`. Was this issue created before then or was it officially decided to go for `dispatch_list`?

**Comment by Marenz** [comment]
It does seem a bit dusty...

**Comment by thomas-nicolai-frequenz** [comment]
Closing it as we decided against it @matthias-wende-frequenz FYI
