### ISSUE TITLE
Reoccurring dispatches

### ISSUE THREAD

**Issue by thomas-nicolai-frequenz** [frequenz-floss/frequenz-api-dispatch#9]
### What's needed?

What is need is the ability to request reoccurring dispatch requests. By reoccurring I mean the ability to schedule reoccurring events like e.g. that every Monday morning a battery should be charged.

For the start we need the ability to repeat a dispatch request in a given interval or at certain times. Here is a list of feature we will need 

1. Repeat every day at a given time
2. Repeat at certain day every n week.
3. Repeat every hour 
...

### Proposed solution

Extend the dispatch message to have an optional repeats field. Based upon @llucax suggestion to take some inspiration from the [iCal](https://datatracker.ietf.org/doc/html/rfc5545#section-3.3.10) standard an extension of the current protofbuf spec could look like the following:

```Protobuf
  // import "google/protobuf/timestamp.proto";

message RecurrenceRule {
  enum Frequency {
    HOURLY = 0;
    DAILY = 1;
    WEEKLY = 2;
    MONTHLY = 3;
    YEARLY = 4;
  }

  Frequency freq = 1;          // Frequency of recurrence
  sint32 interval = 2;         // Interval between each freq
  sint32 count = 3;            // Number of occurrences
  google.protobuf.Timestamp until = 4;  // A date-time specifying end of recurrence
  repeated sint32 byhour = 5;       // Hour of the day
  repeated sint32 byday = 6;        // Day of the week
  repeated sint32 bymonthday = 7;   // Day of the month
  repeated sint32 byyearday = 8;    // Day of the year
  repeated sint32 byweekno = 9;     // Week number of the year
  repeated sint32 bymonth = 10;     // Month of the year
  repeated sint32 bysetpos = 11;    // Position in the set of recurrence instances
  bool wkst = 12;                   // The day that the workweek starts
}

message DispatchRequest {  // example dispatch request message
  string id = 1;  // Dispatch ID
  google.protobuf.Timestamp start = 2; // Start time of the event
  google.protobuf.Timestamp end = 3;   // End time of the event
  RecurrenceRule rrule = 4;    // Recurrence rule for this dispatch request
}
```

If `until` or `count` isn't set, the dispatch request will repeat indefinitely.

The `start` and `end` fields represent the time span of the event, whether it's repeating or not. If the event is a one-off event, `start` and `end` must specify the exact date and time of the event, because there's no recurrence rule to determine any other occurrences. If the event is a repeating event, `start` and `end` specify the time span of the event for the first occurrence. The recurrence rule then uses that start time as the base for determining subsequent occurrences.

For example, if there is a dispatch request that starts at "2023-06-13T00:00:00" (midnight at the start of June 13th, 2023) and ends at "2023-06-13T04:00:00" (4am on the same day), and the `RecurrenceRule` specifies `DAILY` frequency, the result  will be a repeating dispatch request that occurs every day from midnight to 4am, starting on June 13th, 2023.

The `start` and `end` fields, combined with the `RecurrenceRule`, are used to define the entire sequence of occurrences for a repeating event. However, in each individual occurrence, the `start` and `end` still just specify the time span of that occurrence.

Here are some examples on how it might work:

**Example 1: Request dispatch once without reoccurrence**

To schedule a dispatch request that just runs once on e.g. the next Monday, there would be no reoccurrence rule and the start date being set to when the dispatch is suppose to `start`, same with the `end` date. 

**Example 2: Dispatch request to reoccur at a given interval 0:30, 1:30, 2:30 etc.**

If something repeats every hour on the half-hour mark, the `RecurrenceRule` would be set to `HOURLY` `frequency` and `byminute` set to 30. The `start` time of the event should be set to the first occurrence time, such as "0:30". `byminute` would have to be set to 30, which means the event happens on the half-hour of every hour.

**Example 3: Repeating every day from 0:00a to 4:00a**

In this case, `freq` is set to `DAILY`, which means the event repeats every day. `start` is set to the time when the event starts (e.g., "0:00"), and `end` is set to the time when the event ends (e.g., "4:00"). `interval` needs to be set to 1 in `RecurrenceRule` to make it repeat daily without skipping any day.

**Example 4: Repeating every day at 10a and 2p**

If there is a dispatch request to be repeated every day, but it only happens at 10 AM and 2 PM. In that case, one would set the `freq` field to `DAILY` and the `byhour` field to `[10, 14]`. This indicates that the event occurs every day at both 10 AM and 2 PM.

### Use cases

1. Schedule to charge a battery at a certain point in time on a daily basis.
2. Run certain services repeatedly at a certain point in time.

### Alternatives and workarounds

An app would have to create each individual dispatch request on a reoccurring basis.

### Additional context

https://datatracker.ietf.org/doc/html/rfc5545#section-3.3.10

**Comment by llucax** [comment]
I wonder how we should deal with overlapping. Following this example:

> For example, if there is a dispatch request that starts at "2023-06-13T00:00:00" (midnight at the start of June 13th, 2023) and ends at "2023-06-13T04:00:00" (4am on the same day), and the RecurrenceRule specifies DAILY frequency, the result will be a repeating dispatch request that occurs every day from midnight to 4am, starting on June 13th, 2023.

If the `end` is `2023-06-14T01:00:00` (i.e. it lasts 25 hours), then the next reocurring dispatch will start before the previous was ended. Should these dispatches be rejected somehow? Or will the dispatch simply be *active* **all the time**?

**Comment by thomas-nicolai-frequenz** [comment]
I only see two choices:

1. Rejecting overlapping dispatches: We could check and see if the next occurrence of a dispatch request would start before the current occurrence ends.

2. Allow overlapping dispatches: Alternatively, we could allow the creation of overlapping dispatches. In this case, there might be periods where two instances of the dispatch are active at the same time.

To be honest I would vote for solution 1 as I can't oversee the consequences of allowed overlapping dispatches, hence I'd say we stay a little more conservative.

**Comment by llucax** [comment]
I agree that allowing overlapping dispatches doesn't seem to have any sense and could lead to very weird problems (like if a FCR dispatch is overlapping, when the start time of the overlapping occurrence is hit, should we reset everything and start over? If not then it is basically ignoring the second occurrence and just extending the original one?).  Probably not worth it.

For the first option I still see 2 choices though: Who is rejecting, the dispatch service (so the dispatch is not created at all)? The actor will just ignore overlapping dispatches considering them invalid? I think the later can lead to very weird cases where dispatches are unexpectedly not executed because there is a mistake creating the dispatch and it results in an overlapping dispatch and ignored because it is invalid, but for the later we'll have to implement (at least partially) the logic to check reoccurring dispatches in the service too (for now we said it should stay in the actor).

I think even when it might be more effort, it makes sense to reject dispatches in the service, there is no point in storing an invalid dispatch and it will be more user-friendly, failing as soon as possible, not 3 weeks later when your dispatch is supposed to get executed.

**Comment by thomas-nicolai-frequenz** [comment]
> Who is rejecting, the dispatch service (so the dispatch is not created at all)?

Dispatch service as well as the dispatch actor. Both should check for inconsistencies and irregular schedules. The service can be buggy or broken, hence both sides need to check for these things. "Everything that can fail will fail" ;-)

**Comment by llucax** [comment]
Yeah, yeah, I didn't meant if it was in the service the actor will just trust it, but the actor will have to implement all the logic, so the check is almost for free anyway :)

**Comment by stefan-brus-frequenz** [comment]
Some questions:

- `  repeated sint32 byweekno = 9;     // Week number of the year`. How should this field work? For example, let's say that we get a dispatch with the start time `2023-06-13T00:00:00`, and the `byweekno` values 20, 34, 51. Should it just figure out what weekday 2023-06-13 is, and schedule a dispatch for that same day and time in each of those numerical weeks?
- `  repeated sint32 bysetpos = 11;    // Position in the set of recurrence instances`. Can you give an example that uses this field? I'm not entirely sure what it's for. My assumption would be a kind of index for when `count` is set to a certain value?
- `  bool wkst = 12;                   // The day that the workweek starts` What is this field used for?

**Comment by stefan-brus-frequenz** [comment]
As for the implementation: Should the recurrence rule be considered a property of the dispatch itself? The dispatch service could keep the current dispatch structure, and create new dispatch instances (DB rows, in practice) based on what the recurrence rule specifies. That way the actor logic could be kept simple, without having to worry about parsing and verifying the recurrence rule field. I could see this being a problem for infinitely recurring dispatches, though.

**Comment by thomas-nicolai-frequenz** [comment]
> That way the actor logic could be kept simple, without having to worry about parsing and verifying the recurrence rule field.

Right, I think we discussed this somewhere. I suggest we also extend the dispatch actor. Lets assume something has to repeat once per hour for 15-min and runs infinite. We'd have to send a lot of data and hope the the LTE connection always works and thats too much of "hope". I'm afraid we won't get around submitting the recurrence rule to the edge if follow the "everything can fail" rule plus we would do a lot of communication. @leandro-lucarella-frequenz whats your take on that?

**Comment by thomas-nicolai-frequenz** [comment]
> bool wkst = 12;   // The day that the workweek starts What is this field used for?

1. the day that is considered as the start of the week
2. it affects calculations for weekly recurring events
3. right now Sunday (false) and Monday (true)

We could extend it to use an enum instead like:

```Protobuf
enum WeekStart {
  SUNDAY = 0;
  MONDAY = 1;
}
WeekStart wkst = 1;  // The day that the week starts
```

Of course we can also remove this and simply say we don't support weekly recurring events for now. I'm also fine with that. What you think?

**Comment by thomas-nicolai-frequenz** [comment]
> repeated sint32 bysetpos = 11;    // Position in the set of recurrence instances. Can you give an example that uses this field?

This can be used to adjust the first instance to be selected from the other "BYxxx" rules. If you for example choose the following `FREQ=MONTHLY;BYDAY=MO,TU,WE,TH,FR;BYSETPOS=-1`, it would only select FR. If you set it to 1 it would only select MO. If you set it to 2 it would only TU.

I'm not quite sure we exactly need it tbh. This is from the iCal specification. We can also remove this for now and support it later on if needed.

Note: In the iCalendar specification, -1 is used to indicate the last item in a sequence or a list.

**Comment by thomas-nicolai-frequenz** [comment]
> repeated sint32 byweekno = 9;     // Week number of the year. How should this field work? For example, let's say that we get a dispatch with the start time 2023-06-13T00:00:00, and the byweekno values 20, 34, 51. Should it just figure out what weekday 2023-06-13 is, and schedule a dispatch for that same day and time in each of those numerical weeks?

Some notes before:
* Weeks are numbered as defined in ISO 8601
* iCalendar recurrence rule specifies which weeks of the year the event should occur in
* Week 1 is the first week that has at least 4 days in the new year, and with Monday as the first day of the week.

Given your example, if there is a start date on 2023-06-13T00:00:00, and BYWEEKNO values are 20, 34, 51, the dispatch will be scheduled on the same weekday as the start date (which is a Tuesday) during the 20th, 34th, and 51st weeks of each year.

We'd set `FREQ=YEARLY;BYWEEKNO=20,34,51`, then a dispatch would occur yearly on the same weekday as the start date, but only during the 20th, 34th, and 51st weeks of the year. The exact dates would depend on how the weeks fall in a given year.

**Comment by llucax** [comment]
> Right, I think we discussed this somewhere. I suggest we also extend the dispatch actor. Lets assume something has to repeat once per hour for 15-min and runs infinite. We'd have to send a lot of data and hope the the LTE connection always works and thats too much of "hope". I'm afraid we won't get around submitting the recurrence rule to the edge if follow the "everything can fail" rule plus we would do a lot of communication. @leandro-lucarella-frequenz whats your take on that?

Yeah, I was also saying that, that even when it would be nice to remove this complexity from the actor, it will be more reliable and efficient to have the reoccurring specification in the dispatch and let the actor handle the scheduling. This also plays well with the design we had in mind with one channel for announcing new dispatch messages arrived and one channel to receive exactly when a dispatch should be executed.

```py
async def run():
    # dispatch helper sends out dispatches when they are due
    dispatch_arrived, dispatch_ready = dispatch_helper.new_receivers()
    
    async for msg in Select(dispatch_ready, dispatch_arrived):
        dispatch = msg.consume()
        if msg is dispatch_arrived:
            # This produces a new message each time a reoccurring dispatch should be executed
            match dispatch.type:
            DISPATCH_TYPE_BATTERY_CHARGE
                battery_pool = microgrid.battery_pool(dispatch.battery_set, task_id)
                battery_pool.set_charge(dispatch.power)
            ...
        if msg is dispatch_arrived:
            # This produces only one message for new dispatches, even if they are reoccurring
            log.info("New dispatch arrived %s", dispatch)
```

**Comment by llucax** [comment]
> Of course we can also remove this and simply say we don't support weekly recurring events for now. I'm also fine with that. What you think?

I don't understand why should we make which days is considered the start of the week configurable. Can we just say arbitrarily that it is always Monday (or Sunday, or whatever we want) and just stick with that?

**Comment by llucax** [comment]
If we want to follow the icalendar spec and we want the service not to care about reoccurring events, then it might be better to just make reocurrence a text field storing the icalendar representation of the reocurrence.  This might not be super orthodox, but it would be super practical, because all these issues we are having about how to interpret stuff is already done and we can just use existing implementations, for example [icalendar](https://pypi.org/project/icalendar/) (which is [very popular and well maintained](https://snyk.io/advisor/python/icalendar)) and related projects:

> Related projects
> 
> * [icalevents](https://github.com/irgangla/icalevents). It is built on top of icalendar and allows you to query iCal files and get the events happening on specific dates. It manages recurrent events as well.
> 
> * [recurring-ical-events](https://pypi.org/project/recurring-ical-events/). Library to query an ICalendar object for events happening at a certain date or within a certain time.

I guess for the UI there should also be libraries to help with creating ical events.

**Comment by stefan-brus-frequenz** [comment]
> I don't understand why should we make which days is considered the start of the week configurable. Can we just say arbitrarily that it is always Monday (or Sunday, or whatever we want) and just stick with that?

+1, I think this would add too much complexity for very little reward

**Comment by thomas-nicolai-frequenz** [comment]
> I don't understand why should we make which days is considered the start of the week configurable. Can we just say arbitrarily that it is always Monday (or Sunday, or whatever we want) and just stick with that?

In that case we should remove the feature entirely to be able to say I always want to schedule something at the beginning of the work week and only allow absolute scheduling by providing the exact day of the week. Otherwise it will simply be wrong because not in all regions of the world the workweek starts on Monday thus you might end up charging a battery on a completely wrong day. That would be very bad.

**Comment by thomas-nicolai-frequenz** [comment]
> If we want to follow the icalendar spec and we want the service not to care about reoccurring events, then it might be better to just make reocurrence a text field storing the icalendar representation of the reocurrence. 

I would not suggest doing that. In that case the question would quickly come up why we don't do it for everything and always. I also see very limited benefit as we start diverging from the standard already. We have removed quite a few features and we may keep doing so in the future. At that point the benefit isn't there anymore. Lets not start messing up the clear and precise Protobuf definitions please. Maybe I'm being a bit too conservative here but the rest of the scheduling wouldn't be a string but the reoccurring part would be. That feels inconsistent.

**Comment by llucax** [comment]
> In that case we should remove the feature entirely to be able to say I always want to schedule something at the beginning of the work week and only allow absolute scheduling by providing the exact day of the week. Otherwise it will simply be wrong because not in all regions of the world the workweek starts on Monday thus you might end up charging a battery on a completely wrong day. That would be very bad.

Ah, ok, so this would be to have an abstract way to say "I want this to start when the week begins" and not tie to "Monday" or "Sunday". I guess this makes sense in ical, as it probably needs to deal with multiple countries, but in here it will be scheduled for a location where this is known I guess, so the UI could deal with presenting Monday or Sunday as the start of the week depending on users preferences, but encode the absolute value in the generated dispatch.

**Comment by llucax** [comment]
> I would not suggest doing that. In that case the question would quickly come up why we don't do it for everything and always. I also see very limited benefit as we start diverging from the standard already. We have removed quite a few features and we may keep doing so in the future. At that point the benefit isn't there anymore. Lets not start messing up the clear and precise Protobuf definitions please. Maybe I'm being a bit too conservative here but the rest of the scheduling wouldn't be a string but the reoccurring part would be. That feels inconsistent.

I see your points. I think removing features is not a problem though, as with overlapping events, that could be checked, but the internal representation could still be ical, even if there are features we will forbid (pretty much like C++, that has thousands of features but most people forbid using half of them to keep the sanity :laughing: ).

The scheduling will be a string but not a random one, it will be a string following a very well known and standard specification, this is why for me it would be not ideal (as you say it is inconsistent) but acceptable.

For me the benefit of it is we save the work of coding the scheduling, but it is true that if at the end we use a very limited subset, the implementation should also be simple so using an external library is not as beneficial.

**Comment by thomas-nicolai-frequenz** [comment]
> I guess this makes sense in ical, as it probably needs to deal with multiple countries, but in here it will be scheduled for a location where this is known I guess

uhhh very careful with this. Keep in mind you might deploy the same code in different locations and now you need to tweak the code because Monday is Sunday ;-) I'm happy to remove this feature for now but this means manual tweaking of code for maybe a lot of locations (might not scale well)

> so the UI could deal with presenting Monday or Sunday as the start of the week depending on users preferences, but encode the absolute value in the generated dispatch.

Please ignore the UI. Our main use case is apps that are setting and managing these reoccurring dispatches. I'm ok to have the app figure out the start of the week instead of it happen in the dispatch actor. Thats fine to me.

**Comment by thomas-nicolai-frequenz** [comment]
> I see your points. I think removing features is not a problem though, as with overlapping events, that could be checked, but the internal representation could still be ical

I've been thinking about this and we are mixing two things up.
1. Interface definition (representation)
2. Internal (object) representation & logic inside an ical implementation

I'm still very much oppose to using a string representation when we can stay coherent with explicit Protobuf fields. Otherwise I don't understand why we use Protobuf after all and just make everything a string. The more important part though is the string representation is anyway turned into an object by any ical implementation. That means representation and (internal) validation logic are two different things. Thus we can still use every ical implementation to check the validity no matter the representation. The string is turned into an object by pretty much every ical implementation because otherwise checking validity is impossible. Sticking with protobuf even means we are even saving the overhead of parsing the string and turning it into an internal object representation. We can have the best of both worlds is what I'm trying to say here.

**Comment by llucax** [comment]
> uhhh very careful with this. Keep in mind you might deploy the same code in different locations and now you need to tweak the code because Monday is Sunday ;-) I'm happy to remove this feature for now but this means manual tweaking of code for maybe a lot of locations (might not scale well)

No, this is not what I meant, what I meant is that our internal representation doesn't have any ambiguity, for example we decide day 0 is Sunday, 1 is Monday, etc. We don't care about an "abstract" start of the week. ~Then the UI presents to the user Sunday or Monday as the start of the week (but shows no "abstract" option "start of the week", but will still use 1 for Monday even if to that user Monday was shown as the start of the week). Not sure if it is clear.~ (ignoring the UI now :P)

**Comment by llucax** [comment]
> I'm still very much oppose to using a string representation when we can stay coherent with explicit Protobuf fields.

I'm fine with this, it was just an idea to use an existing standard (and tools around it).

> Otherwise I don't understand why we use Protobuf after all and just make everything a string.

Because the string is not just a string, it is a **standard** that happens to be encoded in a string.

> Thus we can still use every ical implementation to check the validity no matter the representation.

This depends a lot on how the library(ies) we want to use are designed, they might not offer this intermediate representation and even if we do, we would have to convert our internal representation to the one used by the library, so I'm not sure it will be saving us much work. It will depend a lot on what we find in existing libraries.

> Sticking with protobuf even means we are even saving the overhead of parsing the string and turning it into an internal object representation.

I don't think parsing the string is an overhead that would have any weight in this discussion, is not like we are going to process thousands of dispatch messages for a location anyway.

> We can have the best of both worlds is what I'm trying to say here.

And this is what I don't see, at least not clearly (if you mean we can represent stuff in protobuf fields **and** use a ical-based library to calculate the schedules). Maybe it works, maybe it doesn't, but we either need to mimic ical's structure 1:1 with the string encoding or we need to have a translation layer, which adds more complexity.

It is a lot of speculation without getting into the details of the existing libraries.

Personally I would go one way or the other: either we do our own thing encoding directly in protobuf, inspired by ical but removing features we don't think we need and trying to come up with the simplest specification that works for us, or we decide to be ical-compatible and use ical encoding to store ical schedules.

Another thing if we want to be ical-compatible but encode in our own way is, any other API consumer will have to deal with our own ical schedules encoding on their own, while if we use the standard ical string ecoding, they can just throw the schedule field to their favorite ical library in their favorite programming language and they are ready to go. If we go our own way, every API consumer will have to reimplement this logic over (or at least the translation layer) and over again, which is not particularly great. Even in our own dispatch service, if we want to do some validation on the schedule, we'll have to implement in rust too.

Once more, I'm OK with our own thing, but I still think there is non-trivial value in using the standard ical encoding and I don't see this intermediate option as the best of both worlds so clearly.

**Comment by thomas-nicolai-frequenz** [comment]
> Personally I would go one way or the other: either we do our own thing encoding directly in protobuf, inspired by ical but removing features we don't think we need and trying to come up with the simplest specification that works for us, or we decide to be ical-compatible and use ical encoding to store ical schedules.

I'm clearly voting for the first option. I'm just afraid we opening up a broader discussion of when to use Protobuf or not. Its like wrapping one protocol in another. I'd really favour a pure Protobuf approach and not a mixture of two protocols. I'd choose the second approach if someone would want to export an ical event from his calendar and somehow import it into the UI. But I can't see that use case for now.

**Comment by thomas-nicolai-frequenz** [comment]
> Once more, I'm OK with our own thing, but I still think there is non-trivial value in using the standard ical encoding and I don't see this intermediate option as the best of both worlds so clearly.

Yes, you could say its a false hope that the exiting libraries do offer this kind of functionality and that its not somewhere defined as private. But in Python there is no such thing lol

**Comment by Marenz** [comment]
I feel it's a bit strong to call ical a protocol in this context. It's a format, usually for a file. 
If we were to send jpegs we also wouldn't translate that into protobuf pixel arrays :) 

Given the context and frequency this will be used I think we should maximize compatibility rather than consistency.

**Comment by stefan-brus-frequenz** [comment]
> I feel it's a bit strong to call ical a protocol in this context. It's a format, usually for a file. If we were to send jpegs we also wouldn't translate that into protobuf pixel arrays :)
> 
> Given the context and frequency this will be used I think we should maximize compatibility rather than consistency.

+1 to this. Do we plan on supporting drag-and-drop iCal events in the UI for creating dispatches?

**Comment by thomas-nicolai-frequenz** [comment]
Alright @leandro-lucarella-frequenz I think the real trouble would kick in if someone would use the ICal text based standard and insert features we don't support. In this moment we'd need to build a wrapper around the libraries or something that handles that. If we do use Protobuf instead this problem would not exist as the interface itself would prevent that from happening imho

In consequence that means we'd need to write that somewhere into the documentation rather having the interface do it for us. Is that really better and does it suite our purpose? We can easily turn the protobuf fields into the string if we want to and feed it internally into the libraries if needed. Thats why easier then doing the opposite. 
Maybe we can even skip that by accessing some underlying (private functions) where we get access to the libraries internal data structures as certainly these libraries are mapping the text to an internal data structure. That also means that the argument that we need to use the text string iCal standard in order to use these libraries is not holding up.

And here you can see how it can work and everything is exposed as public:
https://icalendar.readthedocs.io/en/latest/_modules/icalendar/prop.html#vRecur

The more I look at it the less I'm convinced we should be dealing with this string approach and define a clear Protobuf interface as defined above as otherwise we have to define everywhere of what we are not supporting according to the Ical standard. On top we would need to implement this limitations in each of the libraries we are using.

**Comment by thomas-nicolai-frequenz** [comment]
> Do we plan on supporting drag-and-drop iCal events in the UI for creating dispatches?

No. It would create exactly the problems I described above and the UI is also not our main use case. Our main use case are apps that would create those rather than human beings.

**Comment by thomas-nicolai-frequenz** [comment]
> if we were to send jpegs we also wouldn't translate that into protobuf pixel arrays

Does every pixel in a jpeg has its own entry in a RFC ;-) This is comparing apples with oranges.

**Comment by llucax** [comment]
> Alright @leandro-lucarella-frequenz

This time it wasn't me! :laughing: 

I find your concerns reasonable and I am fine with using our own (protobuf) definition for reoccurrence. :+1:

**Comment by thomas-nicolai-frequenz** [comment]
Based upon the discussions I shared in the slack channel here is a slightly stripped down version that more complies with the cron standard:

```Protobuf

// RecurrenceRule specifies the rules for when a recurring event should occur.
// This implementation tries to adhere to the iCalendar specification (RFC 5545),
// particularly section 3.3.10 (Recurrence Rule). We use the same field names based
// on that RFC so it can be used as a reference for the semantics of each field.
//
// Note: Not all features of the RFC 5545 are implemented, this is a simplified version
// tailored to common needs. For more details on the semantics of each field, refer to the RFC 5545.
message RecurrenceRule {
  // Frequency interval
  enum Frequency {
    MINUTELY = 0;
    HOURLY = 1;
    DAILY = 2;
    WEEKLY = 3;
    MONTHLY = 4;
  }

  // Days of the week.
  enum Weekday {
    MONDAY = 0;
    TUESDAY = 1;
    WEDNESDAY = 2;
    THURSDAY = 3;
    FRIDAY = 4;
    SATURDAY = 5;
    SUNDAY = 6;
  }
  
  Frequency freq = 1;

  // Specifies how often the event recurs, based on the frequency.
  // For example, if frequency is DAILY and interval is 2, the event will occur every two days.
  sint32 interval = 2; 

  // Limit the number of occurrences. For example, if count is 5, the event will only occur 5 times.
  optional sint32 count = 3; 

  // Specify on which hours of the day the event occurs.
  repeated sint32 byhour = 4;

  // Specify on which minutes of the hour the event occurs.
  repeated sint32 byminute = 5;

  // Specify on which days of the week the event occurs.
  repeated Weekday byday = 6;

  // Specify on which days of the month the event occurs.
  repeated sint32 bymonthday = 7;

  // Specify in which months the event occurs.
  repeated sint32 bymonth = 8;
}

message RecurringEvent {
  // Start time of the event.
  google.protobuf.Timestamp start = 1; 
  
  // End time of the event. It must be after the start time.
  optional google.protobuf.Timestamp end = 2;
  
  // Defines the recurrence pattern for the event.
  RecurrenceRule rrule = 3;  
}
```

A usage example would be:  schedule to run at the 30min mark on every hour
```Protobuf
message RecurringEvent {
  start { seconds: 1623567600 }  // 2023-06-13T00:30:00 in UNIX timestamp (this is just for the time reference, the exact date can be arbitrary if you are going for a daily repetition).
  rrule {
    freq: HOURLY
    byminute: [30]
  }
}
```

**Comment by llucax** [comment]
We should make sure to mention also that we are going to try to stick to the iCal spec ([RFC 5545](https://datatracker.ietf.org/doc/html/rfc5545), in particular the [section 3.3.10 (Recurrence Rule)](https://datatracker.ietf.org/doc/html/rfc5545#section-3.3.10)), so we are using the same field names based on that, so we can also use it as a reference to get more info on the semantics of each field.

**Comment by thomas-nicolai-frequenz** [comment]
> We should make sure to mention also that we are going to try to stick to the iCal spec

done in the [definition](https://github.com/frequenz-floss/frequenz-api-dispatch/issues/9#issuecomment-1697942075) above.
